#!/bin/sh
# set keyboard layout to Swiss German
setxkbmap ch

# start hotkey daemon
xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config &

# set some defaults
export BROWSER=firefox &
export EDITOR=vim &

# set (previous) wallpaper
~/.cache/.fehbg && mv ~/.fehbg ~/.cache

# turn off BIOS beeper
xset b off

# set WM name (for Java apps)
wmname LG3D

# load notification deamon
dunst &

# load composite manager
#xcompmgr -c &
picom &

# swap caps and escape (for vim users)
setxkbmap -option caps:swapescape

# set brightness
brightnessctl -d $(brightnessctl -l | grep "class 'backlight'" | head -n 1 | awk '{print $2}' | tr -d "'") set $(cat ~/.config/norisa/brightness-state)%

# load dwmblocks
dwmblocks &

# don't display mouse if not used recently
unclutter &

# ~/ cleanup
rm -r "$HOME/go"
rm "$HOME/.mupdf.history"

# run dwm
exec dwm
