#!/bin/sh

device=$(brightnessctl -l | grep "class 'backlight'" | head -n 1 | awk '{print $2}' | tr -d "'")
brightness=$(brightnessctl -d "${device}" | grep Current | awk -F '[)(]' '{print $2}')

printf "🔆 %s\\n" "$brightness"
