#!/bin/bash

# script to display the network state in dwmblocks

wifi=$(iwgetid -r)
upstate=$(ip a | grep BROADCAST,MULTICAST, | awk '{print $9}')
if [[ "x$wifi" = "x" ]];
    then
        printf "%s\\n" "🔌 $upstate"
    else
        # printf "%s\\n" "📶 $wifi"
        awk '/^\s*w/ { print "📶", int($3 * 100 / 70) "%" }' /proc/net/wireless | sed 's/100/99/'
    fi
