#!/bin/sh

# record main display

xrandr | grep '\*' | head -n 1 | awk '{print }'

[ ! -d "$HOME/vids/screencasts" ] && mkdir -p "$HOME/vids/screencasts"

ffmpeg -f x11grab -r 60 -s 1366x768 -i :0.0 -acodec acc -vcodec libx264 -crf 0 "$HOME/vids/screencasts/$(date +"%F--%H-%M-%S--%N").mkv" &

notify-send "screencasting" "started"
