#!/bin/sh

brightness0=$(brightnessctl -d "amdgpu_bl0" get)
brightness1=$(expr "$brightness0" \* 100)
brightness2=$(expr "$brightness1" / 256)

printf "%s" "$brightness2" > ~/.config/norisa/brightness-state
